apiVersion: v1
kind: Service
metadata:
  name: sample-service
spec:
  type: LoadBalancer
  selector:
    app: sample-go-web-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8081
    nodePort: 32509
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8081
    nodePort: 30846
